## Read the CellProfiler generated feature profiles from the author

In [ ]:
import sqlite3
import pandas as pd

db_path = '/data/user/fangxy/CU/BR00116991.sqlite'
conn = sqlite3.connect(db_path)

cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
table_names = cursor.fetchall()
print(table_names)

[('Image',), ('Nuclei',), ('Cytoplasm',), ('Cells',)]

In [ ]:
table_name = 'Cells'
df = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5;", conn)

df
# conn.close()

,TableNumber,ImageNumber,ObjectNumber,Cells_AreaShape_Area,Cells_AreaShape_BoundingBoxArea,Cells_AreaShape_BoundingBoxMaximum_X,Cells_AreaShape_BoundingBoxMaximum_Y,Cells_AreaShape_BoundingBoxMinimum_X,Cells_AreaShape_BoundingBoxMinimum_Y,Cells_AreaShape_Center_X,...,Cells_Texture_Variance_RNA_10_02_256,Cells_Texture_Variance_RNA_10_03_256,Cells_Texture_Variance_RNA_3_00_256,Cells_Texture_Variance_RNA_3_01_256,Cells_Texture_Variance_RNA_3_02_256,Cells_Texture_Variance_RNA_3_03_256,Cells_Texture_Variance_RNA_5_00_256,Cells_Texture_Variance_RNA_5_01_256,Cells_Texture_Variance_RNA_5_02_256,Cells_Texture_Variance_RNA_5_03_256
0,23447007214922264442756958720161958863,1,1,1834,2464,175,44,119,0,147.422028,...,147.255399,151.782533,164.783547,157.673994,159.758863,160.663670,164.541613,155.780611,154.535859,157.297191
1,23447007214922264442756958720161958863,1,2,4808,6386,1058,62,955,0,1007.803661,...,221.602144,229.829795,209.246179,210.898976,211.154497,211.361926,208.812846,212.769787,212.604465,214.217267
2,23447007214922264442756958720161958863,1,3,4274,7920,280,102,200,3,246.671502,...,45.044602,49.697043,44.796783,44.472828,44.292483,45.082537,45.317305,45.013340,44.392656,46.072086
3,23447007214922264442756958720161958863,1,4,9510,14605,966,115,839,0,895.859832,...,99.497074,102.390836,91.943509,93.593273,93.004898,93.436252,92.644306,95.924668,94.488928,95.535426
4,23447007214922264442756958720161958863,1,5,7919,11644,351,142,269,0,306.717767,...,94.847745,100.607697,93.259798,93.833051,93.084008,94.067810,94.226012,95.204466,93.601934,95.733731

## Read our own CellProfiler generated feature profiles

In [ ]:
import pandas as pd

csv_path = "/data/user/fangxy/CU/drug_cell/output_csv/Cells.csv"

df = pd.read_csv(csv_path)

df.columns

Index(['ImageNumber', 'ObjectNumber', 'AreaShape_Area',
       'AreaShape_BoundingBoxArea', 'AreaShape_BoundingBoxMaximum_X',
       'AreaShape_BoundingBoxMaximum_Y', 'AreaShape_BoundingBoxMinimum_X',
       'AreaShape_BoundingBoxMinimum_Y', 'AreaShape_Center_X',
       'AreaShape_Center_Y',
       ...
       'Texture_Variance_OrigRNA_10_02_256',
       'Texture_Variance_OrigRNA_10_03_256',
       'Texture_Variance_OrigRNA_3_00_256',
       'Texture_Variance_OrigRNA_3_01_256',
       'Texture_Variance_OrigRNA_3_02_256',
       'Texture_Variance_OrigRNA_3_03_256',
       'Texture_Variance_OrigRNA_5_00_256',
       'Texture_Variance_OrigRNA_5_01_256',
       'Texture_Variance_OrigRNA_5_02_256',
       'Texture_Variance_OrigRNA_5_03_256'],
      dtype='object', length=282)